plugins {
    id 'dev.architectury.loom' version '1.10.455'
    id 'architectury-plugin' version '3.4.164'
}

architectury {
    minecraft = minecraft_version
    forge()
}

loom {
    forge {
        mixinConfig "dragoncare.mixins.json"
    }
    mixin {
        defaultRefmapName = "dragoncare-refmap.json"
    }
}

group = maven_group
version = mod_version

base {
    archivesName = archives_name
}

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'FabricOnly'
                url = "https://maven.fabricmc.net/"
            }
        }
        filter { includeGroup 'net.fabricmc' }
    }
    exclusiveContent {
        forRepository {
            maven {
                name = 'ArchitecturyMirrorOnly'
                url = "https://maven.creeperhost.net/"
            }
        }
        filter { includeGroupByRegex 'dev\\.architectury(\\..*)?' }
    }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraft:minecraft:${minecraft_version}"
    mappings loom.layered {
        it.mappings("net.fabricmc:yarn:${yarn_mappings}:v2")
    }
    
    forge "net.minecraftforge:forge:${forge_version}"

    modImplementation files('libs/IceAndFireCE-1.2.5-1.20.1-forge.jar')
    modImplementation files('libs/uranus-2.2.6-bugfix.2-1.20.1-forge.jar')
    modRuntimeOnly files('libs/jupiter-2.3.7-1.20.1-forge.jar')
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 17
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-Xlint:all,-processing', '-Werror']
}

processResources {
    def modVersion = project.version
    inputs.property 'version', modVersion
    from('CREDITS.txt')
    filesMatching('META-INF/mods.toml') {
        expand version: modVersion
    }
}
